Repository cse110-sp21-group13/cse110-sp21-group13, pull requests merged in 2021-06, with the labels that each got.

#140 [BUG/FE] Nav bar click to close
  source/docs/assets/js/nav.js
  source/docs/nav.html
Labels: bug, frontend

#145 [BUG/FE] Calendar Skipping Month
  source/docs/assets/js/calendar.js
Labels: bug, frontend

#147 [BUG/QE] Update on Testing of delete/user
  source/__tests__/bullet.test.js
  source/__tests__/user.test.js
  source/routes/delete/user-data.js
  source/routes/read/user-data.js
Labels: S, enhancement, qe, sprint 3, testing

#150 [BUG/QE] Add Test to Testings on users + sessions
  source/__tests__/user.test.js
Labels: enhancement, qe, sprint 3, testing

#148 [STRY/FE] Restrict Future Dailies
  source/docs/assets/js/daily.js
Labels: S, enhancement, frontend, sprint 3

#152 [STRY/QE] Unit test on Month.js
  source/__tests__/month.test.js
Labels: S, qe, sprint 3, testing

#153 [STRY/FE] User Data Management in Navbar
  source/docs/assets/css/nav.css
  source/docs/assets/js/nav.js
  source/docs/nav.html
  source/jsdocs/scripts/linenumber.js
  source/jsdocs/scripts/prettify/lang-css.js
  source/jsdocs/scripts/prettify/prettify.js
Labels: enhancement, frontend

#137 [STRY/FE] Deleting/Editing bullets
  source/docs/assets/js/journal.js
  source/routes/delete/bullet.js
  source/routes/read/daily.js
Labels: M, enhancement, frontend, sprint 3

#123 [STRY/FE] Master CSS Doc
  source/docs/assets/css/calendar.css
  source/docs/assets/css/contrast-style.css
  source/docs/assets/css/daily.css
  source/docs/assets/css/dark-style.css
  source/docs/assets/css/index.css
  source/docs/assets/css/journal.css
  source/docs/assets/css/light-style.css
  source/docs/assets/css/migration.css
  source/docs/assets/css/nav.css
  source/docs/assets/images/dailyblob.svg
  source/docs/assets/images/leftblob.svg
  source/docs/assets/images/pinkblobmain.svg
  source/docs/assets/images/pinkblobmain2.svg
  source/docs/calendar.html
  source/docs/daily.html
  source/docs/index.html
  source/docs/journal.html
  source/docs/migration.html
  source/docs/nav.html
  source/package-lock.json
Labels: enhancement, frontend, sprint 2

#157 [STRY/FE] Add Favicon
  source/docs/assets/images/favicon.ico
  source/docs/calendar.html
  source/docs/daily.html
  source/docs/future.html
  source/docs/index.html
  source/docs/migration.html
Labels: enhancement, frontend

#158 ADR Updates
  specs/adrs/0009-one-day-migration.md
  specs/adrs/0010-express.md
  specs/adrs/0011-passport.md
Labels: documentation

#160 [STRY/FE] Calendar Style Improvements
  source/docs/assets/css/calendar.css
  source/docs/assets/css/contrast-style.css
  source/docs/assets/css/dark-style.css
  source/docs/assets/css/light-style.css
  source/docs/assets/js/calendar.js
  source/docs/calendar.html
Labels: enhancement, frontend

#162 [STRY/QE] Login E2E Testing
  source/__tests__/login.test.js
  source/jest-puppeteer.config.js
Labels: S, qe, testing

#163 [STRY/QE] Login E2E Testing
  source/__tests__/login.test.js
  source/jest-puppeteer.config.js
Labels: S, qe, testing

#164 [STRY/QE] Nav Bar E2E Testing
  source/__tests__/login.test.js
  source/__tests__/nav.test.js
Labels: M, qe, sprint 3, testing

#168 [STRY/QE] Daily E2E Testing
  source/__tests__/daily.test.js
Labels: qe, sprint 3, testing

#170 [STRY/QE] Future Log E2E Testing
  source/__tests__/future.test.js
Labels: qe, sprint 3, testing

#173 [BUG/FE] Fix Calendar Daily Links in Calendar if Month DNE Yet
  source/docs/assets/js/calendar.js
Labels: bug, frontend

#167 hifi update
  specs/interface/highfidelity/contrast_daily.png
  specs/interface/highfidelity/contrast_migration.png
  specs/interface/highfidelity/contrast_monthly.png
  specs/interface/highfidelity/contrast_monthly_menu_open.png
  specs/interface/highfidelity/daily_log_hifi.png
  specs/interface/highfidelity/dark_daily.png
  specs/interface/highfidelity/dark_migration.png
  specs/interface/highfidelity/dark_monthly.png
  specs/interface/highfidelity/dark_monthly_menu_open.png
  specs/interface/highfidelity/future_log_hifi.png
  specs/interface/highfidelity/homepage_menu_open_hifi.png
  specs/interface/highfidelity/homepage_menu_open_if_signed_in_hifi.png
  specs/interface/highfidelity/homepage_no_menu_open_hifi.png
  specs/interface/highfidelity/light_daily.png
  specs/interface/highfidelity/light_homepage.png
  specs/interface/highfidelity/light_login.png
  specs/interface/highfidelity/light_migration.png
  specs/interface/highfidelity/light_monthly.png
  specs/interface/highfidelity/light_monthly_menu_open.png
  specs/interface/highfidelity/login_hifi.png
  specs/interface/highfidelity/monthly_hifi.png
Labels: documentation

#175 wireframe updates
  specs/interface/highfidelity/contrast_daily.png
  specs/interface/highfidelity/contrast_migration.png
  specs/interface/highfidelity/contrast_monthly.png
  specs/interface/highfidelity/contrast_monthly_menu_open.png
  specs/interface/highfidelity/dark_daily.png
  specs/interface/highfidelity/dark_migration.png
  specs/interface/highfidelity/dark_monthly.png
  specs/interface/highfidelity/dark_monthly_menu_open.png
  specs/interface/highfidelity/light_daily.png
  specs/interface/highfidelity/light_migration.png
  specs/interface/rough/screen4_future_log.png
  specs/interface/rough/screen4_migration.png
  specs/interface/wireframes/daily_log.png
  specs/interface/wireframes/future_log.png
  specs/interface/wireframes/homepage - menu open.png
  specs/interface/wireframes/homepage - no menu open.png
  specs/interface/wireframes/login.png
  specs/interface/wireframes/monthly.png
  specs/interface/wireframes/wf_daily.png
  specs/interface/wireframes/wf_homepage.png
  specs/interface/wireframes/wf_login.png
  specs/interface/wireframes/wf_migration.png
  specs/interface/wireframes/wf_monthly.png
  specs/interface/wireframes/wf_monthly_menu_open.png
Labels: documentation

#171 Scratch/feture/codacy modify
  .github/workflows/codacyReporter.yml
  cobertura.xml
  source/coverage/clover.xml
  source/coverage/coverage-final.json
  source/coverage/lcov-report/base.css
  source/coverage/lcov-report/block-navigation.js
  source/coverage/lcov-report/favicon.png
  source/coverage/lcov-report/index.html
  source/coverage/lcov-report/prettify.css
  source/coverage/lcov-report/prettify.js
  source/coverage/lcov-report/sort-arrow-sprite.png
  source/coverage/lcov-report/sorter.js
  source/coverage/lcov-report/source/index.html
  source/coverage/lcov-report/source/middleware/authenticate.js.html
  source/coverage/lcov-report/source/middleware/index.html
  source/coverage/lcov-report/source/routes/create/bullet.js.html
  source/coverage/lcov-report/source/routes/create/daily.js.html
  source/coverage/lcov-report/source/routes/create/index.html
  source/coverage/lcov-report/source/routes/create/month.js.html
  source/coverage/lcov-report/source/routes/create/session.js.html
  source/coverage/lcov-report/source/routes/create/user.js.html
  source/coverage/lcov-report/source/routes/delete/bullet.js.html
  source/coverage/lcov-report/source/routes/delete/daily.js.html
  source/coverage/lcov-report/source/routes/delete/index.html
  source/coverage/lcov-report/source/routes/delete/month.js.html
  source/coverage/lcov-report/source/routes/delete/session.js.html
  source/coverage/lcov-report/source/routes/delete/user-data.js.html
  source/coverage/lcov-report/source/routes/read/bullet.js.html
  source/coverage/lcov-report/source/routes/read/daily.js.html
  source/coverage/lcov-report/source/routes/read/index.html
  source/coverage/lcov-report/source/routes/read/month.js.html
  source/coverage/lcov-report/source/routes/read/user-data.js.html
  source/coverage/lcov-report/source/routes/read/user.js.html
  source/coverage/lcov-report/source/routes/update/bullet.js.html
  source/coverage/lcov-report/source/routes/update/daily.js.html
  source/coverage/lcov-report/source/routes/update/index.html
  source/coverage/lcov-report/source/routes/update/month.js.html
  source/coverage/lcov-report/source/routes/update/user.js.html
  source/coverage/lcov-report/source/services/index.html
  source/coverage/lcov-report/source/services/setup_passport.js.html
  source/coverage/lcov-report/source/start.js.html
  source/coverage/lcov.info
Labels: bug, qe

#176 [STRY/QE] Calendar E2E testing
  source/__tests__/calendar.test.js
Labels: qe, sprint 3, testing

#182 [BUG/FE] Minor README bug
  README.md
Labels: bug, frontend

#178 [STRY/QE] Host JSDocs in seperate repo
  .github/workflows/JSDocs.yml
Labels: enhancement, qe, sprint 3

#179 lighthouse reports
  specs/testing_docs/daily_lighthouse_report.pdf
  specs/testing_docs/login_lighthouse_report.pdf
  specs/testing_docs/monthly_lighthouse_report.pdf
Labels: documentation, qe

#180 Update README.md
  README.md
Labels: S, documentation

#183 Update readme to include figma link
  README.md
Labels: documentation

#185 [STRY/QE] Pipeline documentation final update
  admin/cipipeline/phase1-final.md
  admin/cipipeline/phase1.png
Labels: documentation, qe, sprint 3

#186 Updating readme section and link
  README.md
Labels: bug, documentation
