Repository cse110-sp21-group13/cse110-sp21-group13, pull requests merged in 2021-05, with the labels that each got.

#46 Uploaded nav bar html to be added to other pages
  source/docs/assets/images/13bullet_logo.png
  source/docs/nav.html
Labels: enhancement, frontend, sprint 1

#50 [BUG/FE] Logo file path incorrect
  source/docs/index.html
  source/docs/login.html
Labels: bug, frontend

#53 [STRY/FE] Added nav bar to other HTML pages
  source/docs/calendar.html
  source/docs/daily.html
  source/docs/future.html
  source/docs/index.html
  source/docs/login.html
Labels: frontend, sprint 1

#51 [STRY/BE] Agnostic Document Updater
  source/scripts/updateFields.js
Labels: S, backend, enhancement, sprint 1

#43 [STRY/BE] REST API: Users & Passport Setup
  source/middleware/authenticate.js
  source/package-lock.json
  source/package.json
  source/routes/create/session.js
  source/routes/create/user.js
  source/routes/delete/session.js
  source/routes/delete/user.js
  source/routes/read/user.js
  source/routes/update/user.js
  source/services/setup_passport.js
  source/start.js
Labels: backend, enhancement, sprint 1

#52 [STRY/BE] REST API: Daily Journal Entries
  source/package-lock.json
  source/package.json
  source/routes/create/daily.js
  source/routes/delete/daily.js
  source/routes/read/daily.js
  source/routes/update/daily.js
Labels: backend, enhancement, sprint 1

#62 [BUG/BE] Camelcase in updateFields.js
  source/scripts/update_fields.js
Labels: backend, bug

#60 [BUG/BE] Daily Creation Fails to Store Pre-Given Bullets
  source/routes/create/daily.js
Labels: backend, bug

#64 [STRY/QE] Setup automated documenation (JSDocs)
  .github/workflows/JSDocs.yml
  .github/workflows/codacyReporter.yml
  cobertura.xml
  source/start.js
Labels: enhancement, qe

#128 [STRY/QE] Use Heroku for Testing and Demo
  source/package.json
  source/start.js
Labels: enhancement

#125 [BUG/QE] Pipeline stability fixes
  .github/workflows/node.js.yml
  source/docs/assets/js/journal.js
  source/docs/assets/js/nav.js
  source/docs/assets/js/style.js
  source/jest-puppeteer.config.js
  source/package.json
  source/start.js
Labels: bug, qe, sprint 3

#126 [BUG/QE] Update on User Test after modification of Update Routes
  source/__tests__/user.test.js
Labels: enhancement, qe

#130 [STRY/FE] Migration
  source/docs/assets/css/migration.css
  source/docs/assets/js/calendar.js
  source/docs/assets/js/journal.js
  source/docs/assets/js/migration.js
  source/docs/migration.html
  source/routes/read/month.js
Labels: M, frontend, sprint 3

#121 [STRY/QE] Testing Bullet CRUD
  source/__tests__/bullet.test.js
  source/__tests__/start.test.js
  source/__tests__/user.test.js
  source/jsdocs/docs_assets_js_daily.js.html
  source/jsdocs/docs_assets_js_journal.js.html
  source/jsdocs/global.html
  source/jsdocs/index.html
  source/jsdocs/routes_delete_daily.js.html
  source/jsdocs/scripts_update_fields.js.html
  source/jsdocs/start.js.html
  source/package-lock.json
  source/package.json
  source/start.js
Labels: enhancement, qe

#131 ADR Updates
  source/docs/assets/js/migration.js
  specs/adrs/0007-iframe-bullets.md
  specs/adrs/0008-only-deletion.md
  specs/adrs/0009-one-day-migration
Labels: S, documentation, sprint 3

#106 [STRY/QE] Testing Daily CRUD
  source/__tests__/daily-crud.test.js
  source/__tests__/start.test.js
  source/jsdocs/docs_assets_js_daily.js.html
  source/jsdocs/global.html
Labels: sprint 2, testing

#136 [BUG/FE] User already exists error
  source/docs/assets/js/login.js
Labels: bug, frontend

#133 [STRY/BE] User Deletion/Download Routes
  source/routes/delete/user-data.js
  source/routes/delete/user.js
  source/routes/read/user-data.js
Labels: backend, enhancement
